Repository cBarbosa/iris-gestao, pull requests merged in 2022-12, with the labels that each got.

#10 Develop
  .vscode/launch.json
  IrisGestao/IrisSpa/src/app/app-routing.module.ts
  IrisGestao/IrisSpa/src/app/app.component.scss
  IrisGestao/IrisSpa/src/app/layout/logged-in/topbar/topbar.component.scss
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.scss
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.module.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register.component.scss
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register.module.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-view/client-view-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-view/client-view.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-view/client-view.component.scss
  IrisGestao/IrisSpa/src/app/pages/client/client-view/client-view.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-view/client-view.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.module.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.html
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.scss
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.spec.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.module.ts
  IrisGestao/IrisSpa/src/app/shared/services/client.service.ts
  IrisGestao/IrisSpa/src/app/shared/utils/utils.ts
  IrisGestao/IrisSpa/src/environments/environment.ts
  IrisGestao/IrisSpa/src/index.html
  IrisGestao/IrisSpa/src/styles.scss
Labels: enhancement

#14 Feature/real estate
  .gitignore
  IrisGestao/IrisApi/IrisAppService/Repository/Interfaces/IClienteRepository.cs
  IrisGestao/IrisApi/IrisAppService/Repository/Interfaces/IImovelRepository.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ClienteService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ImovelEnderecoService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ImovelService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/UnidadeService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IClienteService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IImovelService.cs
  IrisGestao/IrisApi/IrisConsole/Program.cs
  IrisGestao/IrisApi/IrisDomain/Command/Request/CriarImovelCommand.cs
  IrisGestao/IrisApi/IrisDomain/Emuns/TipoImovelEnum.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Anexo.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Cliente.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Contato.cs
  IrisGestao/IrisApi/IrisDomain/Entity/ContratoAluguel.cs
  IrisGestao/IrisApi/IrisDomain/Entity/ContratoFornecedor.cs
  IrisGestao/IrisApi/IrisDomain/Entity/DadoBancario.cs
  IrisGestao/IrisApi/IrisDomain/Entity/DespesaLocatario.cs
  IrisGestao/IrisApi/IrisDomain/Entity/DespesaProprietario.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Evento.cs
  IrisGestao/IrisApi/IrisDomain/Entity/FaturaTitulo.cs
  IrisGestao/IrisApi/IrisDomain/Entity/FormaPagamento.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Fornecedor.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Imovel.cs
  IrisGestao/IrisApi/IrisDomain/Entity/ImovelEndereco.cs
  IrisGestao/IrisApi/IrisDomain/Entity/NotaFiscal.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Obra.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Orcamento.cs
  IrisGestao/IrisApi/IrisDomain/Entity/TipoCliente.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Titulo.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Unidade.cs
  IrisGestao/IrisApi/IrisInfra/ORM/IrisContext.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ClienteRepository.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ClienteController.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ImovelController.cs
  IrisGestao/IrisSpa/src/app/layout/logged-in/topbar/topbar.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.html
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel.model.spec.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel.model.ts
  IrisGestao/IrisSpa/src/app/shared/models/index.ts
  IrisGestao/IrisSpa/src/app/shared/services/index.ts
  IrisGestao/IrisSpa/src/app/shared/services/property.service.ts
Labels: enhancement

#16 Listagem de clientes via API
  IrisGestao/IrisApi/.vs/IrisGestao/v17/.suo
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.ts
Labels: bug, documentation, enhancement

#17 Função de reconhecimento de rota (topBar)
  IrisGestao/IrisSpa/src/app/app-routing.module.ts
  IrisGestao/IrisSpa/src/app/layout/logged-in/topbar/topbar.component.ts
Labels: documentation

#19 Feature/real estate
  .vscode/launch.json
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisSpa/src/app/app-routing.module.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.html
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.module.ts
Labels: documentation, enhancement

#21 Develop
  IrisGestao/IrisSpa/src/app/app-routing.module.ts
  IrisGestao/IrisSpa/src/app/auth/auth.module.ts
  IrisGestao/IrisSpa/src/app/auth/iframe/iframe.component.html
  IrisGestao/IrisSpa/src/app/auth/iframe/iframe.component.ts
  IrisGestao/IrisSpa/src/app/auth/login/login.component.ts
  IrisGestao/IrisSpa/src/app/layout/logged-in/topbar/topbar.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/client/client.module.ts
  IrisGestao/IrisSpa/src/app/pages/home/home-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/home/home.component.html
  IrisGestao/IrisSpa/src/app/pages/home/home.component.scss
  IrisGestao/IrisSpa/src/app/pages/home/home.component.ts
  IrisGestao/IrisSpa/src/app/pages/home/home.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property.module.ts
  IrisGestao/IrisSpa/src/app/shared/components/photo-gallery/photo-gallery.component.html
  IrisGestao/IrisSpa/src/app/shared/components/photo-gallery/photo-gallery.component.scss
  IrisGestao/IrisSpa/src/app/shared/components/photo-gallery/photo-gallery.component.ts
  IrisGestao/IrisSpa/src/app/shared/helpers/auth/auth.guard.ts
Labels: enhancement

#22 Feat: view property detail
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisSpa/src/app/pages/property/property-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.module.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel-unidade.model.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel.model.ts
  IrisGestao/IrisSpa/src/app/shared/services/imovel.service.ts
Labels: enhancement

#26 Paginação e spinner de loading na listagem de imóveis
  IrisGestao/IrisSpa/src/app/app.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-listing/property-listing.module.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-list/property-list.component.html
  IrisGestao/IrisSpa/src/app/shared/components/property-list/property-list.component.scss
  IrisGestao/IrisSpa/src/app/shared/components/property-list/property-list.component.ts
Labels: documentation, enhancement

#27 Feat: get unit data by guid
  IrisGestao/IrisApi/IrisAppService/Repository/Interfaces/IUnidadeRepository.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/UnidadeService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IUnidadeService.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/UnidadeRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/UnidadeController.cs
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel-unidade.model.ts
  IrisGestao/IrisSpa/src/app/shared/services/imovel.service.ts
Labels: enhancement

#28 Feat: unit stuffs
  IrisGestao/IrisApi/IrisAppService/Repository/Interfaces/IUnidadeRepository.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ImovelService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/UnidadeService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IUnidadeService.cs
  IrisGestao/IrisApi/IrisDomain/Command/Request/CriarImovelCommand.cs
  IrisGestao/IrisApi/IrisDomain/Command/Request/CriarUnidadeCommand.cs
  IrisGestao/IrisApi/IrisDomain/Entity/Unidade.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/UnidadeRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ImovelController.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/UnidadeController.cs
Labels: enhancement

#30 Feat: list property owners
  IrisGestao/IrisApi/IrisAppService/Repository/Interfaces/IClienteRepository.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ClienteService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IClienteService.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ClienteRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ClienteController.cs
Labels: enhancement

#32 Feat: update unit
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/shared/models/imovel-unidade-tipo.model.spec.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel-unidade-tipo.model.ts
  IrisGestao/IrisSpa/src/app/shared/models/imovel-unidade.model.ts
  IrisGestao/IrisSpa/src/app/shared/models/index.ts
  IrisGestao/IrisSpa/src/app/shared/services/imovel.service.ts
Labels: enhancement

#45 Feat: owners list and update property
  IrisGestao/IrisApi/IrisAppService/Service/Impl/UnidadeService.cs
  IrisGestao/IrisApi/IrisDomain/Command/Request/CriarUnidadeCommand.cs
  IrisGestao/IrisApi/IrisDomain/Emuns/TipoClienteEnum.cs
  IrisGestao/IrisApi/IrisDomain/Emuns/TipoUnidadeEnum.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ClienteRepository.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/UnidadeRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ImovelController.cs
  IrisGestao/IrisSpa/src/app/pages/home/home.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.html
  IrisGestao/IrisSpa/src/app/shared/models/imovel.model.ts
Labels: enhancement

#47 Fix: some property fixes
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.ts
Labels: bug

#49 Feat: Update unit
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register-routing.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.html
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.spec.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.module.ts
  IrisGestao/IrisSpa/src/app/shared/services/imovel.service.ts
Labels: enhancement

#50 Feature/edit property
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/unit-edit/unit-edit.component.html
  IrisGestao/IrisSpa/src/app/pages/property/unit-edit/unit-edit.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/unit-edit/unit-edit.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-edit/unit-edit.module.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.html
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/unit-register/unit-register.module.ts
  IrisGestao/IrisSpa/src/app/shared/components/property-item/property-item.component.html
  IrisGestao/IrisSpa/src/app/shared/models/cliente.model.ts
Labels: bug

#51 Fix: property register
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.ts
Labels: bug

#57 Feat: clone unit
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ImovelService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/UnidadeService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IUnidadeService.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/UnidadeController.cs
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.scss
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-view/property-view.module.ts
  IrisGestao/IrisSpa/src/app/shared/services/imovel.service.ts
Labels: enhancement

#59 Feat: get address by zipcode
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ImovelEnderecoService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/ExternalService/IRepublicaVirtualService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Interface/IImovelEnderecoService.cs
  IrisGestao/IrisApi/IrisInfra/ExternalServices/RepublicaVirtualService.cs
  IrisGestao/IrisApi/IrisInfra/IoC/IoCRegisterServices.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ImovelEnderecoController.cs
Labels: enhancement

#61 Feat: add address to property & paging to customers
  IrisGestao/IrisApi/IrisAppService/Repository/Interfaces/IImovelEnderecoRepository.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ClienteService.cs
  IrisGestao/IrisApi/IrisAppService/Service/Impl/ImovelService.cs
  IrisGestao/IrisApi/IrisDomain/Command/Request/CriarImovelCommand.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ClienteRepository.cs
  IrisGestao/IrisApi/IrisInfra/Repository/Impl/ImovelEnderecoRepository.cs
  IrisGestao/IrisApi/IrisWebApi/Controllers/ClienteController.cs
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-listing/client-listing.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register.component.html
  IrisGestao/IrisSpa/src/app/pages/client/client-register/client-register.component.ts
  IrisGestao/IrisSpa/src/app/pages/client/client-view/client-view.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-edit/property-edit.component.ts
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.html
  IrisGestao/IrisSpa/src/app/pages/property/property-register/property-register.component.ts
  IrisGestao/IrisSpa/src/app/shared/models/cliente.model.ts
  IrisGestao/IrisSpa/src/app/shared/services/index.ts
Labels: bug, enhancement
